### PR TITLE
change to standalone dialog

### PR DESCRIPTION
**Pull request by Marr11317**
Here's the good PR, compare with your version.

### CODE REVIEW

**Comment by Marr11317** [comment]
Reindented

**Comment by Marr11317** [comment]
yep. You should still test it. There might be cases I forgot.
I hope there's no drawback too, but that's a question for dmitrio. I'll ask on the developper chat.

**Comment by Marr11317** [comment]
Also, It should probably be a separate issue, but could you add translation files? I would gladly take care of french for all your plugins.

One last thing, you probably know that a plugin manager is coming soon (3.6). This plugin manager installs a whole git repo. This is why they recommend to create one plugin per git repo, so that they can be downloaded individually. I don't how this will evolve anyhow.

**Comment by Marr11317** [comment]
Here's the version after the commit:
image

And before:
image

It looks like some more work would have to be done for this to work properly. However, I can't manage to put notes, in after this commit, and before. 

It may be that I am not using it properly. Here's a screencast:

**Comment by BernardGreenberg** [comment]
The OK button shouldn't even be there.  The Apply button is supposed to do the deed -- let me check it...
________________________________

**Comment by BernardGreenberg** [comment]
That's all it is! If you hit "Apply" instead oof OK, it works properly!

So just make the OK go away....
________________________________

**Comment by Marr11317** [comment]
Oooh.! The ok button is the default button appearing on a dialog. Easy fix

**Comment by Marr11317** [comment]
see https://github.com/BernardGreenberg/MuseScorePlugins/pull/4

**Comment by BernardGreenberg** [comment]
Looks good. lemme try it.
________________________________

**Comment by Marr11317** [comment]
Don't try this one. Try the new PR.

**Comment by BernardGreenberg** [comment]
Did I merge the right one?
________________________________

**Comment by Marr11317** [comment]
yes

**Pull request closed without merging**
