### PR TITLE
change to automatic buttons

### PR DESCRIPTION
**Pull request by Marr11317**
a little less verbose, more platform-styled and automatically translated by Qt

### CODE REVIEW

**Comment by BernardGreenberg** [comment]
I'll deal with this tomorrow. I upgraded the file to change its version and change notices.
________________________________

**Comment by Marr11317** [comment]
Sure, no need to rush

**Comment by BernardGreenberg** [comment]
All the other MS plugins, esp TempoChanges, have to change.
________________________________

**Comment by BernardGreenberg** [comment]
I assume you tested it functionally....
________________________________

**Comment by Marr11317** [comment]
I did. Here's the behaviour, translated in french:

image

**Comment by BernardGreenberg** [comment]
Cute!
________________________________

**Pull request merged**
